services:
    beanstalkd:
        container_name: beanstalkd
        image: schickling/beanstalkd
        ports:
          - "11300:11300"
    redis-rdb:
        container_name: redis-rdb
        image: redis:latest
        environment:
          - REDIS_RDB_POLICY_DISABLED=no
          - REDIS_RDB_POLICY="900#1 300#10"
        ports:
          - "6379:6379"
    redis-aof:
        container_name: redis-aof
        image: redis:latest
        environment:
          REDIS_AOF_ENABLED: yes
          REDIS_AOF_FSYNC: everysec
          ALLOW_EMPTY_PASSWORD: yes
        ports:
          - "6380:6379"
